from fpdf import FPDF
import os
import uuid
from datetime import datetime

class PDF(FPDF):
    def __init__(self, logo_path=None):
        super().__init__()
        self.logo_path = logo_path

    def header(self):
        # Logo
        if self.logo_path and os.path.exists(self.logo_path):
            self.image(self.logo_path, 10, 8, 25)
        
        # Clinic Info (Right Aligned or Centered)
        self.set_font('Arial', 'B', 18)
        self.set_text_color(14, 165, 233) # Sky Blue
        self.cell(0, 10, "Smart Dermatology Diagnosis using AI", 0, 1, 'C')
        
        self.set_font('Arial', 'B', 10)
        self.set_text_color(100, 116, 139) # Slate 500
        self.cell(0, 5, "AI-Powered Skin Disease Detection System", 0, 1, 'C')
        self.set_font('Arial', '', 9)
        self.cell(0, 5, "Advanced Machine Learning Diagnostics | 19-Class Disease Classification", 0, 1, 'C')
        
        # Separator Line
        self.ln(5)
        self.set_draw_color(14, 165, 233)
        self.set_line_width(0.5)
        self.line(10, 35, 200, 35)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')
        self.cell(0, 10, 'Generated by Smart Dermatology AI - Not a final medical diagnosis', 0, 0, 'R')

class ReportGenerator:
    def __init__(self, root_path):
        self.root_path = root_path
        self.DESCRIPTION = {
            "acne": "Acne is a common skin condition caused by clogged pores and bacteria. It often appears as comedones, papules, pustules, or cysts/nodules.",
            "hyperpigmentation": "Hyperpigmentation is a common, usually harmless condition in which patches of skin become darker in color than the normal surrounding skin.",
            "nail_psoriasis": "Nail psoriasis is a condition that affects the fingernails and toenails, causing pitting, abnormal nail growth, and discoloration.",
            "sjs-ten": "Stevens-Johnson syndrome (SJS) and toxic epidermal necrolysis (TEN) are severe skin reactions. Immediate medical attention is required.",
            "vitiligo": "Vitiligo is a disease that causes the loss of skin color in blotches. It occurs when pigmnet-producing cells die or stop functioning."
        }

    def clean_text(self, text):
        return str(text).encode("latin-1", "ignore").decode("latin-1")

    def generate(self, username, disease, confidence, severity, original_img_path, gradcam_img_path, output_filename, patient_name=None, gender=None, location=None, state=None, country=None):
        # Locate Logo
        logo_path = os.path.join(self.root_path, "assets", "hospital_logo.png")
        if not os.path.exists(logo_path):
            logo_path = os.path.join(self.root_path, "static", "assets", "hospital_logo.png")

        pdf = PDF(logo_path)
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()
        
        # ---- TITLE ----
        pdf.set_font("Arial", "B", 14)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, "DERMATOLOGICAL ASSESSMENT REPORT", 0, 1, 'C')
        pdf.ln(5)

        # ---- PATIENT BOX ----
        pdf.set_fill_color(248, 250, 252) # Slate 50
        pdf.set_draw_color(226, 232, 240)
        pdf.rect(10, pdf.get_y(), 190, 35, 'FD')
        
        pdf.set_y(pdf.get_y() + 5)
        start_y = pdf.get_y()
        
        # Column 1
        pdf.set_left_margin(15)
        pdf.set_font("Arial", "B", 10)
        pdf.cell(35, 6, "Patient Name:", 0, 0)
        pdf.set_font("Arial", "", 10)
        pdf.cell(60, 6, self.clean_text(patient_name or username), 0, 1)
        
        pdf.set_font("Arial", "B", 10)
        pdf.cell(35, 6, "Gender:", 0, 0)
        pdf.set_font("Arial", "", 10)
        pdf.cell(60, 6, self.clean_text(gender or "Not specified"), 0, 1)
        
        pdf.set_font("Arial", "B", 10)
        pdf.cell(35, 6, "Location:", 0, 0)
        pdf.set_font("Arial", "", 10)
        location_str = f"{location}, {state}, {country}" if all([location, state, country]) else "Not specified"
        pdf.cell(60, 6, self.clean_text(location_str), 0, 1)

        # Column 2 (Reset Y, Move X)
        pdf.set_y(start_y)
        pdf.set_x(110)
        pdf.set_font("Arial", "B", 10)
        pdf.cell(35, 6, "Report ID:", 0, 0)
        pdf.set_font("Arial", "", 10)
        pdf.cell(60, 6, str(uuid.uuid4())[:8].upper(), 0, 1)

        pdf.set_x(110)
        pdf.set_font("Arial", "B", 10)
        pdf.cell(35, 6, "Date:", 0, 0)
        pdf.set_font("Arial", "", 10)
        pdf.cell(60, 6, datetime.now().strftime("%d-%b-%Y"), 0, 1)
        pdf.set_font("Arial", "", 10)
        pdf.cell(50, 6, f"RPT-{datetime.now().strftime('%Y%m%d')}-{int(confidence)}", 0, 1)
        
        pdf.set_x(110)
        pdf.set_font("Arial", "B", 10)
        pdf.cell(35, 6, "Report Date:", 0, 0)
        pdf.set_font("Arial", "", 10)
        pdf.cell(50, 6, datetime.now().strftime("%B %d, %Y"), 0, 1)
        
        pdf.set_x(110)
        pdf.set_font("Arial", "B", 10)
        pdf.cell(35, 6, "System:", 0, 0)
        pdf.set_font("Arial", "", 10)
        pdf.cell(50, 6, "AI Diagnosis v2.0", 0, 1)

        pdf.set_left_margin(10) # Reset margin
        pdf.ln(15)

        # ---- DIAGNOSIS SECTION ----
        pdf.set_font("Arial", "B", 11)
        pdf.set_fill_color(14, 165, 233)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(190, 7, "  Diagnostic Results", 0, 1, 'L', True)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(3)
        
        # Warning/Severity Banner
        if severity == 'High Risk':
            pdf.set_fill_color(254, 202, 202) # Red 200
            pdf.set_text_color(153, 27, 27) # Red 800
        else:
            pdf.set_fill_color(209, 250, 229) # Emerald 200
            pdf.set_text_color(6, 95, 70) # Emerald 800
            
        pdf.set_font("Arial", "B", 11)
        pdf.cell(190, 10, f"  PREDICTED CONDITION: {self.clean_text(disease).upper()} ({severity})", 0, 1, 'L', True)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(3)
        
        # Details
        pdf.set_font("Arial", "B", 9)
        pdf.cell(40, 5, "AI Confidence:", 0, 0)
        pdf.set_font("Arial", "", 9)
        pdf.cell(0, 5, f"{confidence:.2f}% Match", 0, 1)
        
        pdf.set_font("Arial", "B", 9)
        pdf.cell(0, 5, "Clinical Description:", 0, 1)
        pdf.set_font("Arial", "", 9)
        desc = self.DESCRIPTION.get(disease, "No specific description available in database.")
        pdf.multi_cell(0, 5, self.clean_text(desc))
        pdf.ln(5)

        # ---- IMAGES ----
        pdf.set_font("Arial", "B", 11)
        pdf.set_fill_color(241, 245, 249)
        pdf.cell(190, 7, "  Visual Analysis", 0, 1, 'L', True)
        pdf.ln(3)
        
        y_pos = pdf.get_y()
        
        # Draw Image Boxes (Reduced Height)
        pdf.rect(15, y_pos, 85, 55)
        pdf.rect(110, y_pos, 85, 55)
        
        # Labels
        pdf.set_xy(15, y_pos + 56)
        pdf.set_font("Arial", "I", 8)
        pdf.cell(85, 4, "Original Scan", 0, 0, 'C')
        
        pdf.set_xy(110, y_pos + 56)
        pdf.cell(85, 4, "Grad-CAM Heatmap (AI Attention)", 0, 0, 'C')
        
        # Place Images
        if original_img_path and os.path.exists(original_img_path):
            pdf.image(original_img_path, x=16, y=y_pos+1, w=83, h=53)
            
        if gradcam_img_path and os.path.exists(gradcam_img_path):
            pdf.image(gradcam_img_path, x=111, y=y_pos+1, w=83, h=53)
            
        pdf.ln(65)

        # ---- NOTES ----
        pdf.set_font("Arial", "B", 11)
        pdf.cell(190, 7, "  Physician Notes", 0, 1, 'L', False) # No fill
        pdf.set_line_width(0.2)
        pdf.set_draw_color(200)
        for _ in range(2):
            pdf.ln(6)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())

        # Save
        reports_dir = os.path.join(self.root_path, "static", "reports")
        os.makedirs(reports_dir, exist_ok=True)
        
        output_path = os.path.join(reports_dir, output_filename)
        pdf.output(output_path)
        
        return output_path
